---

- name: Check if Python is already installed
  stat:
    path: "{{ bin_path }}/python"
  register: b

- debug:
    msg: "Python already exists"
    verbosity: 2
  when: b.stat.exists

- name: install python
  shell: "{{ bin_path }}/brew install python"
  when: not b.stat.exists

- name: Install Trifacta dependencies
  shell:
    "{{bin_path}}/pip install -r {{trifacta_pathf}}/{{trifacta_namef}}/bin/service-supervisor/requirements.txt"
  args:
    executable: /bin/bash

- debug:
    msg: "Python installed with requirements!"
    verbosity: 2



