---

# create virtual box

- shell: "{{ bin_path }}/docker-machine ls -q | grep {{ machine_name }}"
  register: docker_machine_existing
  ignore_errors: yes

- shell: "{{bin_path}}/docker-machine --debug create --driver virtualbox --virtualbox-memory={{virtualbox_memory}} --virtualbox-disk-size={{virtualbox_disk_size}} {{machine_name}}"
  when: docker_machine_existing.stdout != machine_name

- debug:
    msg: "Docker machine {{machine_name}} created!"
  when: docker_machine_existing.stdout != machine_name

- name: Set up a virtual machine with docker on it - start <machine-name>
  shell: "{{bin_path}}/docker-machine start {{machine_name}}"
  when: docker_machine_existing.stdout != machine_name
  ignore_errors: yes

- debug:
    msg: "Docker machine {{machine_name}} started!"
  when: docker_machine_existing.stdout != machine_name

- debug:
    msg: "Docker machine {{machine_name}} already exists."
  when: docker_machine_existing.stdout == machine_name

- name: Set up a virtual machine with docker on it - configure docker-machine environment
  shell: eval $({{bin_path}}/docker-machine env {{machine_name}})

- name: Check if docker-machine env dev is added to shrc
  shell: cat {{shrc_path}} | grep 'eval $({{bin_path}}/docker-machine env {{machine_name}})'
  register: shrc_b
  ignore_errors: yes

- name: Add the 'docker-machine env dev' command to shrc
  shell: echo "eval $({{bin_path}}/docker-machine env {{machine_name}})" >> {{shrc_path}}
  when: shrc_b.stdout == ""

- debug:
    msg: "Docker machine environment has been set up successfully. Please run 'source {{shrc_path}}' if you are switching to an existing terminal window/tab"

- debug:
    msg: "To test your docker installation, please run 'docker run hello-world' on a separate terminal window"



