---

# create virtual box

- shell: "{{ bin_path }}/docker-machine ls -q | grep {{ machine_name }}"
  register: docker_machine_existing
  ignore_errors : yes

- shell: "{{bin_path}}/docker-machine create -d {{bin_path}}/virtualbox --virtualbox-memory={{virtualbox_memory}} --virtualbox-disk-size={{virtualbox_disk_size}} {{machine_name}}"
  when: docker_machine_existing.stdout != machine_name

- debug:
    msg: "Docker machine {{machine_name}} created!"
  when: docker_machine_existing.stdout != machine_name

- name: Set up a virtual machine with docker on it - start <machine-name>
  shell: "{{bin_path}}/docker-machine start {{machine_name}}"
  when: docker_machine_existing.stdout != machine_name

- debug:
    msg: "Docker machine {{machine_name}} started!"
  when: docker_machine_existing.stdout != machine_name

- debug:
    msg: "Docker machine {{machine_name}} already exists."
  when: docker_machine_existing.stdout == machine_name

- name: Set up a virtual machine with docker on it - configure docker-machine environment
  shell: eval $({{bin_path}}/docker-machine env {{machine_name}})

- name: Add the 'docker-machine env dev' command to bashrc
  shell: echo "eval $({{bin_path}}/docker-machine env {{machine_name}})" >> ~/.bashrc

- debug:
    msg: "Docker machine environment has been set up successfully. Please run 'source ~/.bashrc' if you are switching to an existing terminal window/tab"