---
# Update java home in bashprofile
# {{ javaversion }}

- name: Export if not available
  blockinfile:
    dest: "{{shrc_path}}"
    block: |
      export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
    marker: '# {mark} ANSIBLE MANAGED BLOCK - JAVA HOME'
    insertbefore: BOF
    create: yes

- name: Source bashprofile
  shell: source {{shrc_path}}
  args:
    executable: /bin/bash
