---
# Check
- name: Check if homebrew is already installed
  stat: 
    path: "{{ bin_path }}/brew"
  register: b

- debug:
    msg: "Brew already exists"
    verbosity: 2
  when: b.stat.exists

# Homebrew install
- name: install homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not b.stat.exists

- name: Update brew
  shell: brew update

- debug: 
    msg: "Brew updated"
    verbosity: 2